/**
 * Detection Rule Generator — Generates SIEM & IDS rules directly from CTI IOCs.
 * Supports:
 *  - Sigma (YAML) for SIEM (Elastic, Splunk, Sentinel, QRadar)
 *  - YARA for Endpoint / File hashing
 *  - Suricata / Snort for Network IDS
 *  - KQL (Kusto Query Language) for Microsoft Defender / Sentinel
 *  - Splunk SPL queries
 */

export interface RuleGenerationInput {
  title: string
  description?: string
  severity?: 'low' | 'medium' | 'high' | 'critical'
  iocs: {
    ips: string[]
    domains: string[]
    hashes: string[]
    urls: string[]
  }
}

/**
 * Generate standard Sigma Rule (YAML) adhering to Sigma specification.
 */
export function generateSigmaRule(input: RuleGenerationInput): string {
  const cleanTitle = input.title.replace(/"/g, "'")
  const level = input.severity || 'high'
  const date = new Date().toISOString().split('T')[0]

  const selections: string[] = []

  if (input.iocs.ips.length > 0) {
    const ipList = input.iocs.ips.map((ip) => `            - '${ip}'`).join('\n')
    selections.push(`    selection_network:\n        DestinationIp:\n${ipList}`)
  }

  if (input.iocs.domains.length > 0) {
    const domainList = input.iocs.domains.map((d) => `            - '${d}'`).join('\n')
    selections.push(`    selection_dns:\n        QueryName:\n${domainList}`)
  }

  if (input.iocs.hashes.length > 0) {
    const hashList = input.iocs.hashes.map((h) => `            - '${h}'`).join('\n')
    selections.push(`    selection_hashes:\n        Hashes|contains:\n${hashList}`)
  }

  const selectionKeys: string[] = []
  if (input.iocs.ips.length > 0) selectionKeys.push('selection_network')
  if (input.iocs.domains.length > 0) selectionKeys.push('selection_dns')
  if (input.iocs.hashes.length > 0) selectionKeys.push('selection_hashes')

  const detectionBody = selections.length > 0 ? selections.join('\n') : '    selection:\n        CommandLine|contains: \'\''
  const condition = selectionKeys.length > 0 ? selectionKeys.join(' or ') : 'selection'

  return `title: "AnseIn CTI - ${cleanTitle}"
id: ${crypto.randomUUID ? crypto.randomUUID() : 'c9a2f1b4-7e83-4a1d-9e65-2b4f8c0a9d12'}
status: experimental
description: "Detects network and file activity associated with ${cleanTitle}. Generated by AnseIn Serverless CTI."
references:
    - https://ansein.local
author: AnseIn CTI Automated Engine
date: ${date}
tags:
    - attack.execution
    - attack.initial_access
    - attack.command_and_control
logsource:
    category: network_connection
    product: windows
detection:
${detectionBody}
    condition: ${condition}
falsepositives:
    - Legitimate administrative or external services
level: ${level}
`
}

/**
 * Generate YARA rule for memory/disk hash and keyword matching.
 */
export function generateYaraRule(input: RuleGenerationInput): string {
  const safeName = input.title.replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 40)
  const hashes = input.iocs.hashes
  const domains = input.iocs.domains
  const urls = input.iocs.urls
  const date = new Date().toISOString().split('T')[0]
  const severity = input.severity || 'HIGH'

  // YARA is a FILE/memory scanner, not a network sniffer. File hashes are
  // matched with the hash module (exact, no false positives from log text).
  // Domains/URLs go into a separate memory-strings rule, clearly labelled.
  const md5s = hashes.filter((h) => /^[a-fA-F0-9]{32}$/.test(h))
  const sha1s = hashes.filter((h) => /^[a-fA-F0-9]{40}$/.test(h))
  const sha256s = hashes.filter((h) => /^[a-fA-F0-9]{64}$/.test(h))

  const hashConds: string[] = [
    ...md5s.map((h) => `hash.md5(0, filesize) == "${h.toLowerCase()}"`),
    ...sha1s.map((h) => `hash.sha1(0, filesize) == "${h.toLowerCase()}"`),
    ...sha256s.map((h) => `hash.sha256(0, filesize) == "${h.toLowerCase()}"`),
  ]

  const fileRule = `rule AnseIn_${safeName}_file {
    meta:
        description = "File-hash match for ${input.title.replace(/"/g, "'")}"
        author = "AnseIn CTI Engine"
        date = "${date}"
        severity = "${severity}"
    condition:
        ${hashConds.length > 0 ? hashConds.join(' or ') : 'false'}
}`

  const netStrings: string[] = []
  domains.forEach((d, idx) => {
    netStrings.push(`        $domain_${idx} = "${d.replace(/"/g, '\\"')}" ascii wide nocase`)
  })
  urls.forEach((u, idx) => {
    netStrings.push(`        $url_${idx} = "${u.replace(/"/g, '\\"')}" ascii wide nocase`)
  })

  // YARA 'import "hash"' is required for the file rule; keep both rules in
  // one output so analysts can deploy them together.
  const memRule = netStrings.length > 0 ? `
rule AnseIn_${safeName}_memstrings {
    meta:
        description = "Memory/process-scan strings (C2 domains/URLs) for ${input.title.replace(/"/g, "'")} — memory-only, expect noise on disk"
        author = "AnseIn CTI Engine"
        date = "${date}"
        severity = "${severity}"
    strings:
${netStrings.join('\n')}
    condition:
        any of them
}` : ''

  return `import "hash"

${fileRule}${memRule}
`
}

/**
 * Generate Suricata / Snort IDS rules.
 */
export function generateSuricataRules(input: RuleGenerationInput): string[] {
  const rules: string[] = []
  let sid = 1000001
  const cleanTitle = input.title.replace(/["\\]/g, '')

  for (const ip of input.iocs.ips) {
    rules.push(
      `alert ip any any -> ${ip} any (msg:"AnseIn CTI - Outbound traffic to malicious IP [${cleanTitle}]"; classtype:trojan-activity; sid:${sid++}; rev:1;)`
    )
  }

  for (const domain of input.iocs.domains) {
    const cleanDomain = domain.replace(/["\\]/g, '')
    rules.push(
      `alert dns any any -> any any (msg:"AnseIn CTI - DNS query to malicious domain ${cleanDomain}"; dns.query; content:"${cleanDomain}"; nocase; classtype:trojan-activity; sid:${sid++}; rev:1;)`
    )
  }

  return rules
}

/**
 * Generate KQL queries for Microsoft Defender / Sentinel.
 */
export function generateKqlQuery(input: RuleGenerationInput): string {
  const parts: string[] = []

  if (input.iocs.ips.length > 0) {
    const ipStr = input.iocs.ips.map((ip) => `"${ip}"`).join(', ')
    parts.push(`DeviceNetworkEvents | where RemoteIP in (${ipStr})`)
  }

  if (input.iocs.domains.length > 0) {
    const domStr = input.iocs.domains.map((d) => `"${d}"`).join(', ')
    parts.push(`DnsEvents | where Name in (${domStr})`)
  }

  if (input.iocs.hashes.length > 0) {
    const hashStr = input.iocs.hashes.map((h) => `"${h}"`).join(', ')
    parts.push(`DeviceFileEvents | where SHA256 in (${hashStr}) or MD5 in (${hashStr})`)
  }

  return parts.join('\n// -----------------------------------------\n')
}
