/**
 * Detection Rule Generator — Generates SIEM & IDS rules directly from CTI IOCs.
 * Supports:
 *  - Sigma (YAML) for SIEM (Elastic, Splunk, Sentinel, QRadar)
 *  - YARA for Endpoint / File hashing
 *  - Suricata / Snort for Network IDS
 *  - KQL (Kusto Query Language) for Microsoft Defender / Sentinel
 *  - Splunk SPL queries
 */

export interface RuleGenerationInput {
  title: string
  description?: string
  severity?: 'low' | 'medium' | 'high' | 'critical'
  iocs: {
    ips: string[]
    domains: string[]
    hashes: string[]
    urls: string[]
  }
}

/**
 * Generate standard Sigma Rule (YAML) adhering to Sigma specification.
 */
export function generateSigmaRule(input: RuleGenerationInput): string {
  const cleanTitle = input.title.replace(/"/g, "'")
  const level = input.severity || 'high'
  const date = new Date().toISOString().split('T')[0]

  const selections: string[] = []

  if (input.iocs.ips.length > 0) {
    const ipList = input.iocs.ips.map((ip) => `            - '${ip}'`).join('\n')
    selections.push(`    selection_network:\n        DestinationIp:\n${ipList}`)
  }

  if (input.iocs.domains.length > 0) {
    const domainList = input.iocs.domains.map((d) => `            - '${d}'`).join('\n')
    selections.push(`    selection_dns:\n        QueryName:\n${domainList}`)
  }

  if (input.iocs.hashes.length > 0) {
    const hashList = input.iocs.hashes.map((h) => `            - '${h}'`).join('\n')
    selections.push(`    selection_hashes:\n        Hashes|contains:\n${hashList}`)
  }

  const detectionBody = selections.length > 0 ? selections.join('\n') : '    selection:\n        CommandLine|contains: \'\''
  const condition = selections.length > 0
    ? selections.map((_, idx) => (idx === 0 ? (input.iocs.ips.length ? 'selection_network' : input.iocs.domains.length ? 'selection_dns' : 'selection_hashes') : (input.iocs.domains.length ? ' or selection_dns' : ' or selection_hashes'))).join('')
    : 'selection'

  return `title: "AnseIn CTI - ${cleanTitle}"
id: ${crypto.randomUUID ? crypto.randomUUID() : 'c9a2f1b4-7e83-4a1d-9e65-2b4f8c0a9d12'}
status: experimental
description: "Detects network and file activity associated with ${cleanTitle}. Generated by AnseIn Serverless CTI."
references:
    - https://ansein.local
author: AnseIn CTI Automated Engine
date: ${date}
tags:
    - attack.execution
    - attack.initial_access
    - attack.command_and_control
logsource:
    category: network_connection
    product: windows
detection:
${detectionBody}
    condition: ${condition}
falsepositives:
    - Legitimate administrative or external services
level: ${level}
`
}

/**
 * Generate YARA rule for memory/disk hash and keyword matching.
 */
export function generateYaraRule(input: RuleGenerationInput): string {
  const safeName = input.title.replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 40)
  const hashes = input.iocs.hashes
  const domains = input.iocs.domains

  const stringEntries: string[] = []
  domains.forEach((d, idx) => {
    stringEntries.push(`        $domain_${idx} = "${d}" ascii wide`)
  })

  const hashEntries = hashes.map((h) => `        // Target Hash: ${h}`).join('\n')

  return `rule AnseIn_${safeName} {
    meta:
        description = "Automated YARA rule for ${input.title}"
        author = "AnseIn CTI Engine"
        date = "${new Date().toISOString().split('T')[0]}"
        severity = "${input.severity || 'HIGH'}"
${hashEntries ? hashEntries + '\n' : ''}    strings:
${stringEntries.length > 0 ? stringEntries.join('\n') : '        $placeholder = "MALWARE_INDICATOR"'}
    condition:
        any of them
}
`
}

/**
 * Generate Suricata / Snort IDS rules.
 */
export function generateSuricataRules(input: RuleGenerationInput): string[] {
  const rules: string[] = []
  let sid = 1000001

  for (const ip of input.iocs.ips) {
    rules.push(
      `alert ip any any -> ${ip} any (msg:"AnseIn CTI - Outbound traffic to malicious IP [${input.title}]"; classtype:trojan-activity; sid:${sid++}; rev:1;)`
    )
  }

  for (const domain of input.iocs.domains) {
    rules.push(
      `alert dns any any -> any any (msg:"AnseIn CTI - DNS query to malicious domain ${domain}"; dns.query; content:"${domain}"; nocase; classtype:trojan-activity; sid:${sid++}; rev:1;)`
    )
  }

  return rules
}

/**
 * Generate KQL queries for Microsoft Defender / Sentinel.
 */
export function generateKqlQuery(input: RuleGenerationInput): string {
  const parts: string[] = []

  if (input.iocs.ips.length > 0) {
    const ipStr = input.iocs.ips.map((ip) => `"${ip}"`).join(', ')
    parts.push(`DeviceNetworkEvents | where RemoteIP in (${ipStr})`)
  }

  if (input.iocs.domains.length > 0) {
    const domStr = input.iocs.domains.map((d) => `"${d}"`).join(', ')
    parts.push(`DnsEvents | where Name in (${domStr})`)
  }

  if (input.iocs.hashes.length > 0) {
    const hashStr = input.iocs.hashes.map((h) => `"${h}"`).join(', ')
    parts.push(`DeviceFileEvents | where SHA256 in (${hashStr}) or MD5 in (${hashStr})`)
  }

  return parts.join('\n// -----------------------------------------\n')
}
